# Generated by Django 3.2.15 on 2022-11-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20221107_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
    ]
